"use client";

import { useState, useEffect, useRef } from "react";
import { useTheme } from "@/lib/useTheme";

type CallRecord = {
  id: number;
  scenario: string;
  source_language: string;
  target_language: string;
  transcript: string;
  summary: string;
  translation: string;
  replies: string[];
  date: string;
};

type Group = {
  label: string;
  key: string;
  records: CallRecord[];
};

const SCENARIO_ICONS: Record<string, string> = {
  "General Professional Call": "📞",
  "Software Engineering Job Interview": "💻",
  "Customer Support Dispute": "🛒",
  "Doctor Appointment": "🏥",
  "Bank or Credit Card": "🏦",
  "Landlord or Utilities": "🏠",
  "Ordering Food at a Restaurant": "🍽️",
};

const LANG_FLAGS: Record<string, string> = {
  "English": "🇺🇸",
  "Chinese (中文)": "🇨🇳",
  "Spanish (Español)": "🇪🇸",
  "French (Français)": "🇫🇷",
  "Japanese (日本語)": "🇯🇵",
  "Korean (한국어)": "🇰🇷",
  "Portuguese (Português)": "🇧🇷",
  "Arabic (العربية)": "🇸🇦",
  "Hindi (हिन्दी)": "🇮🇳",
  "German (Deutsch)": "🇩🇪",
  "Vietnamese (Tiếng Việt)": "🇻🇳",
  "Italian (Italiano)": "🇮🇹",
  "Russian (Русский)": "🇷🇺",
  "Dutch (Nederlands)": "🇳🇱",
};

function getFlag(lang: string) { return LANG_FLAGS[lang] ?? "🌐"; }

function groupRecords(records: CallRecord[]): Group[] {
  const now = new Date();
  const today     = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const yesterday = new Date(today); yesterday.setDate(today.getDate() - 1);
  const weekAgo   = new Date(today); weekAgo.setDate(today.getDate() - 7);
  const monthAgo  = new Date(today); monthAgo.setDate(today.getDate() - 30);
  const buckets: Record<string, CallRecord[]> = {};

  for (const r of records) {
    const d = new Date(r.date.replace(" ", "T"));
    const day = new Date(d.getFullYear(), d.getMonth(), d.getDate());
    let key: string;
    if (day >= today)          key = "Today";
    else if (day >= yesterday) key = "Yesterday";
    else if (day >= weekAgo)   key = "Previous 7 Days";
    else if (day >= monthAgo)  key = "Previous 30 Days";
    else key = d.toLocaleString("en-US", { month: "long", year: "numeric" });
    if (!buckets[key]) buckets[key] = [];
    buckets[key].push(r);
  }

  const ORDER = ["Today", "Yesterday", "Previous 7 Days", "Previous 30 Days"];
  return Object.keys(buckets)
    .sort((a, b) => {
      const ai = ORDER.indexOf(a), bi = ORDER.indexOf(b);
      if (ai !== -1 && bi !== -1) return ai - bi;
      if (ai !== -1) return -1; if (bi !== -1) return 1;
      return new Date("1 " + b).getTime() - new Date("1 " + a).getTime();
    })
    .map(key => ({ label: key, key: key.replace(/\s+/g, "-").toLowerCase(), records: buckets[key] }));
}

function exportJSON(records: CallRecord[]) {
  const blob = new Blob([JSON.stringify(records, null, 2)], { type: "application/json" });
  const a = Object.assign(document.createElement("a"), { href: URL.createObjectURL(blob), download: `call-history-${new Date().toISOString().slice(0, 10)}.json` });
  a.click();
}

function exportCSV(records: CallRecord[]) {
  const headers = ["ID","Date","Scenario","Source Language","Target Language","Summary","Transcript","Translation"];
  const rows = records.map(r => [r.id, r.date, `"${r.scenario}"`, r.source_language, r.target_language,
    `"${(r.summary ?? "").replace(/"/g,'""')}"`, `"${(r.transcript ?? "").replace(/"/g,'""')}"`, `"${(r.translation ?? "").replace(/"/g,'""')}"`]);
  const blob = new Blob([[headers.join(","), ...rows.map(r => r.join(","))].join("\n")], { type: "text/csv" });
  const a = Object.assign(document.createElement("a"), { href: URL.createObjectURL(blob), download: `call-history-${new Date().toISOString().slice(0, 10)}.csv` });
  a.click();
}

function exportAllMarkdown(records: CallRecord[]) {
  const sections = records.map(r => {
    const replies = (r.replies ?? []).map((rep, i) => {
      const parts = rep.split("\n").map(p => p.trim()).filter(Boolean);
      return `  ${i + 1}. ${parts[0] ?? rep}${parts[1] ? `\n     *${parts[1]}*` : ""}`;
    }).join("\n");
    return `## Session #${r.id} — ${r.date}
**Scenario:** ${r.scenario} | **Languages:** ${r.source_language} → ${r.target_language}

### Transcript
${r.transcript ?? "_none_"}

### Summary
${r.summary ?? "_none_"}

### Translation (${r.target_language})
${r.translation ?? "_none_"}

### Suggested Replies
${replies || "_none_"}`;
  }).join("\n\n---\n\n");

  const md = `# Call History Export
*Exported: ${new Date().toLocaleString()} · ${records.length} sessions*

---

${sections}

---
*Generated by AI Call Assistant*
`;
  const blob = new Blob([md], { type: "text/markdown" });
  const a = Object.assign(document.createElement("a"), {
    href: URL.createObjectURL(blob),
    download: `call-history-${new Date().toISOString().slice(0,10)}.md`,
  });
  a.click();
}

function exportAllPDF(records: CallRecord[]) {
  const sections = records.map(r => {
    const replies = (r.replies ?? []).map((rep, i) => {
      const parts = rep.split("\n").map(p => p.trim()).filter(Boolean);
      return `<div class="reply"><span class="reply-num">${i+1}</span><div><div class="reply-native">${parts[0] ?? rep}</div>${parts[1] ? `<div class="reply-en">${parts[1]}</div>` : ""}</div></div>`;
    }).join("");
    return `
    <div class="session">
      <div class="session-header">
        <div class="session-title">${r.scenario}</div>
        <div class="session-meta">${r.date} &nbsp;·&nbsp; ${r.source_language} → ${r.target_language}</div>
      </div>
      <div class="block">
        <div class="block-label">📝 Transcript</div>
        <div class="transcript">${(r.transcript ?? "—").replace(/\n/g,"<br>")}</div>
      </div>
      <div class="two-col">
        <div class="block">
          <div class="block-label">⚡ Summary</div>
          <div class="block-body">${r.summary ?? "—"}</div>
        </div>
        <div class="block">
          <div class="block-label">🌐 Translation</div>
          <div class="block-body translation">${r.translation ?? "—"}</div>
        </div>
      </div>
      ${replies ? `<div class="block"><div class="block-label">💬 Suggested Replies</div>${replies}</div>` : ""}
    </div>`;
  }).join("");

  const html = `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Call History Report</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:'Inter',sans-serif;color:#1a1a2e;background:#fff;padding:40px;max-width:860px;margin:0 auto}
  .page-header{border-bottom:3px solid #6366f1;padding-bottom:20px;margin-bottom:32px}
  .page-title{font-size:26px;font-weight:700;margin-bottom:6px}
  .page-meta{font-size:13px;color:#6b7280}
  .session{margin-bottom:36px;padding-bottom:36px;border-bottom:1px solid #e5e7eb;page-break-inside:avoid}
  .session:last-child{border-bottom:none}
  .session-header{background:#f8f9ff;border:1px solid #e0e7ff;border-radius:10px;padding:14px 18px;margin-bottom:16px}
  .session-title{font-size:16px;font-weight:700;color:#1a1a2e;margin-bottom:4px}
  .session-meta{font-size:12px;color:#6b7280}
  .two-col{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-bottom:14px}
  .block{margin-bottom:14px}
  .block-label{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.08em;color:#6366f1;margin-bottom:8px}
  .block-body{font-size:14px;line-height:1.65;color:#374151}
  .transcript{background:#f8f9ff;border:1px solid #e0e7ff;border-radius:8px;padding:12px 14px;font-family:'Courier New',monospace;font-size:12px;line-height:1.6;color:#374151}
  .translation{color:#4338ca;font-style:italic}
  .reply{display:flex;align-items:flex-start;gap:8px;margin-bottom:8px;padding:8px 12px;background:#f8f9ff;border-radius:7px;border:1px solid #e0e7ff}
  .reply-num{width:20px;height:20px;border-radius:50%;background:#6366f1;color:#fff;font-size:10px;font-weight:700;display:flex;align-items:center;justify-content:center;flex-shrink:0;margin-top:2px}
  .reply-native{font-size:13px;font-weight:600}
  .reply-en{font-size:11px;color:#6b7280;font-style:italic;margin-top:2px}
  .footer{margin-top:32px;padding-top:14px;border-top:1px solid #e5e7eb;font-size:11px;color:#9ca3af;text-align:center}
  @media print{body{padding:24px}}
</style></head>
<body>
  <div class="page-header">
    <div class="page-title">📞 Call History Report</div>
    <div class="page-meta">Exported: ${new Date().toLocaleString()} &nbsp;·&nbsp; ${records.length} sessions</div>
  </div>
  ${sections}
  <div class="footer">Generated by AI Call Assistant</div>
  <script>window.onload=()=>{window.print()}<\/script>
</body></html>`;

  const win = window.open("", "_blank");
  if (win) { win.document.write(html); win.document.close(); }
}

function exportSessionMarkdown(r: CallRecord) {
  const replies = (r.replies ?? []).map((rep, i) => {
    const parts = rep.split("\n").map(p => p.trim()).filter(Boolean);
    return `**${i + 1}.** ${parts[0] ?? rep}${parts[1] ? `  \n　　*${parts[1]}*` : ""}`;
  }).join("\n");

  const md = `# Call Session Report
**Date:** ${r.date}
**Scenario:** ${r.scenario}
**Languages:** ${r.source_language} → ${r.target_language}

---

## 📝 Transcript
${r.transcript ?? "_No transcript_"}

---

## ⚡ Summary
${r.summary ?? "_No summary_"}

---

## 🌐 Translation (${r.target_language})
${r.translation ?? "_No translation_"}

---

## 💬 Suggested Replies
${replies || "_No replies_"}

---
*Generated by AI Call Assistant · ${new Date().toLocaleString()}*
`;
  const blob = new Blob([md], { type: "text/markdown" });
  const a = Object.assign(document.createElement("a"), {
    href: URL.createObjectURL(blob),
    download: `session-${r.id}-${r.date.slice(0,10)}.md`,
  });
  a.click();
}

function exportSessionPDF(r: CallRecord) {
  const replies = (r.replies ?? []).map((rep, i) => {
    const parts = rep.split("\n").map(p => p.trim()).filter(Boolean);
    return `<div class="reply"><span class="reply-num">${i + 1}</span><div><div class="reply-native">${parts[0] ?? rep}</div>${parts[1] ? `<div class="reply-en">${parts[1]}</div>` : ""}</div></div>`;
  }).join("");

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Session Report — ${r.date}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Inter', sans-serif; color: #1a1a2e; background: #fff; padding: 48px; max-width: 800px; margin: 0 auto; }
  .header { border-bottom: 3px solid #6366f1; padding-bottom: 24px; margin-bottom: 32px; }
  .title { font-size: 28px; font-weight: 700; color: #1a1a2e; margin-bottom: 12px; }
  .meta { display: flex; gap: 24px; flex-wrap: wrap; }
  .meta-item { display: flex; align-items: center; gap: 6px; font-size: 13px; color: #6b7280; }
  .meta-label { font-weight: 600; color: #374151; }
  .section { margin-bottom: 28px; }
  .section-title { font-size: 13px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #6366f1; margin-bottom: 10px; display: flex; align-items: center; gap: 6px; }
  .section-title::after { content: ''; flex: 1; height: 1px; background: #e5e7eb; }
  .section-body { font-size: 15px; line-height: 1.7; color: #374151; }
  .transcript { background: #f8f9ff; border: 1px solid #e0e7ff; border-radius: 8px; padding: 16px 18px; font-family: 'Courier New', monospace; font-size: 13px; line-height: 1.65; }
  .translation { color: #4338ca; font-style: italic; }
  .reply { display: flex; align-items: flex-start; gap: 10px; margin-bottom: 10px; padding: 10px 14px; background: #f8f9ff; border-radius: 8px; border: 1px solid #e0e7ff; }
  .reply-num { width: 22px; height: 22px; border-radius: 50%; background: #6366f1; color: white; font-size: 11px; font-weight: 700; display: flex; align-items: center; justify-content: center; flex-shrink: 0; margin-top: 2px; }
  .reply-native { font-size: 14px; font-weight: 600; color: #1a1a2e; }
  .reply-en { font-size: 12px; color: #6b7280; margin-top: 2px; font-style: italic; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; text-align: center; }
  @media print { body { padding: 32px; } }
</style>
</head>
<body>
  <div class="header">
    <div class="title">📞 Call Session Report</div>
    <div class="meta">
      <div class="meta-item"><span class="meta-label">Date:</span> ${r.date}</div>
      <div class="meta-item"><span class="meta-label">Scenario:</span> ${r.scenario}</div>
      <div class="meta-item"><span class="meta-label">Languages:</span> ${r.source_language} → ${r.target_language}</div>
    </div>
  </div>
  <div class="section">
    <div class="section-title">📝 Transcript</div>
    <div class="transcript">${(r.transcript ?? "No transcript").replace(/\n/g, "<br>")}</div>
  </div>
  <div class="section">
    <div class="section-title">⚡ Summary</div>
    <div class="section-body">${r.summary ?? "No summary"}</div>
  </div>
  <div class="section">
    <div class="section-title">🌐 Translation (${r.target_language})</div>
    <div class="section-body translation">${r.translation ?? "No translation"}</div>
  </div>
  <div class="section">
    <div class="section-title">💬 Suggested Replies</div>
    ${replies || "<p style='color:#9ca3af;font-size:14px'>No replies</p>"}
  </div>
  <div class="footer">Generated by AI Call Assistant · ${new Date().toLocaleString()}</div>
  <script>window.onload = () => { window.print(); }<\/script>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (win) { win.document.write(html); win.document.close(); }
}

export default function HistoryPage() {
  const { theme, toggleTheme } = useTheme();
  const [records, setRecords]         = useState<CallRecord[]>([]);
  const [loading, setLoading]         = useState(true);
  const [expanded, setExpanded]       = useState<number | null>(null);
  const [activeGroup, setActiveGroup] = useState<string>("");
  const [showExport, setShowExport]   = useState(false);
  const [deletingId, setDeletingId]   = useState<number | null>(null);
  const [search, setSearch]           = useState("");
  const [dateFrom, setDateFrom]       = useState("");  // "YYYY-MM-DD"
  const [dateTo, setDateTo]           = useState("");  // "YYYY-MM-DD"
  const exportRef    = useRef<HTMLDivElement>(null);
  const sectionRefs  = useRef<Record<string, HTMLElement | null>>({});
  const observerRef  = useRef<IntersectionObserver | null>(null);

  useEffect(() => {
    fetch(`${process.env.NEXT_PUBLIC_API_URL}/history`)
      .then(r => r.json()).then(d => { setRecords(d); setLoading(false); })
      .catch(() => setLoading(false));
  }, []);

  const filtered = records.filter(r => {
    // Text search
    if (search.trim()) {
      const q = search.toLowerCase();
      const textMatch = r.scenario?.toLowerCase().includes(q) || r.summary?.toLowerCase().includes(q) ||
             r.transcript?.toLowerCase().includes(q) || r.source_language?.toLowerCase().includes(q) ||
             r.target_language?.toLowerCase().includes(q);
      if (!textMatch) return false;
    }
    // Date range — r.date is "YYYY-MM-DD HH:MM", slice to "YYYY-MM-DD" for comparison
    const recDate = r.date?.slice(0, 10) ?? "";
    if (dateFrom && recDate < dateFrom) return false;
    if (dateTo   && recDate > dateTo)   return false;
    return true;
  });

  const hasActiveFilters = search.trim() || dateFrom || dateTo;
  const clearFilters = () => { setSearch(""); setDateFrom(""); setDateTo(""); };

  const groups = groupRecords(filtered);

  // Ref to block Observer updates briefly after a manual click
  const scrollLockRef = useRef(false);
  const scrollLockTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    observerRef.current?.disconnect();
    observerRef.current = new IntersectionObserver(
      entries => {
        // Don't let Observer override a manual click
        if (scrollLockRef.current) return;
        for (const e of entries) {
          if (e.isIntersecting) setActiveGroup(e.target.getAttribute("data-group") ?? "");
        }
      },
      { rootMargin: "-30% 0px -60% 0px" }
    );
    Object.values(sectionRefs.current).forEach(el => el && observerRef.current!.observe(el));
    return () => observerRef.current?.disconnect();
  }, [groups.length, search]);

  useEffect(() => {
    const h = (e: MouseEvent) => { if (exportRef.current && !exportRef.current.contains(e.target as Node)) setShowExport(false); };
    document.addEventListener("mousedown", h);
    return () => document.removeEventListener("mousedown", h);
  }, []);

  const scrollToGroup = (key: string) => {
    // 1. Immediately update the highlight
    setActiveGroup(key);
    // 2. Lock Observer for ~800ms so it can't undo the highlight mid-scroll
    scrollLockRef.current = true;
    if (scrollLockTimer.current) clearTimeout(scrollLockTimer.current);
    scrollLockTimer.current = setTimeout(() => { scrollLockRef.current = false; }, 800);
    // 3. Scroll
    sectionRefs.current[key]?.scrollIntoView({ behavior: "smooth", block: "start" });
  };
  const handleDelete  = async (id: number) => {
    setDeletingId(id);
    await fetch(`${process.env.NEXT_PUBLIC_API_URL}/history/${id}`, { method: "DELETE" });
    setRecords(prev => prev.filter(r => r.id !== id));
    setDeletingId(null);
    if (expanded === id) setExpanded(null);
  };

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600;700&family=DM+Mono:wght@400;500&display=swap');

        /* ── Theme Variables ── */
        :root, html[data-theme="dark"] {
          --bg:              #0f0f11;
          --bg-subtle:       #131316;
          --bg-card:         rgba(255,255,255,0.03);
          --bg-card-hover:   rgba(255,255,255,0.055);
          --bg-input:        rgba(255,255,255,0.04);
          --bg-btn:          rgba(255,255,255,0.04);
          --bg-btn-hover:    rgba(255,255,255,0.08);
          --bg-menu:         #18181b;
          --bg-sidebar-hover: rgba(255,255,255,0.05);
          --bg-sidebar-active: rgba(99,102,241,0.15);
          --border:          #1f1f23;
          --border-mid:      #27272a;
          --border-high:     #3f3f46;
          --text-primary:    #fafafa;
          --text-secondary:  #a1a1aa;
          --text-dim:        #71717a;
          --text-muted:      #52525b;
          --text-faint:      #3f3f46;
          --accent:          #6366f1;
          --accent-light:    #a5b4fc;
          --accent-mid:      #818cf8;
          --accent-danger:   #f87171;
          --accent-danger-bg: rgba(239,68,68,0.1);
          --translation:     #818cf8;
          --dot-active:      #818cf8;
          --dot-inactive:    #3f3f46;
          --glow-a:          rgba(99,102,241,0.12);
          --glow-b:          rgba(236,72,153,0.08);
          --glow-c:          rgba(16,185,129,0.05);
          --spinner-track:   #27272a;
        }

        html[data-theme="light"] {
          --bg:              #f4f4f6;
          --bg-subtle:       #ebebee;
          --bg-card:         rgba(255,255,255,0.85);
          --bg-card-hover:   rgba(255,255,255,0.98);
          --bg-input:        rgba(255,255,255,0.9);
          --bg-btn:          rgba(255,255,255,0.7);
          --bg-btn-hover:    rgba(255,255,255,0.95);
          --bg-menu:         #ffffff;
          --bg-sidebar-hover: rgba(0,0,0,0.04);
          --bg-sidebar-active: rgba(79,70,229,0.08);
          --border:          #e4e4e7;
          --border-mid:      #d4d4d8;
          --border-high:     #a1a1aa;
          --text-primary:    #0f0f11;
          --text-secondary:  #3f3f46;
          --text-dim:        #52525b;
          --text-muted:      #71717a;
          --text-faint:      #a1a1aa;
          --accent:          #4f46e5;
          --accent-light:    #4f46e5;
          --accent-mid:      #6366f1;
          --accent-danger:   #dc2626;
          --accent-danger-bg: rgba(220,38,38,0.08);
          --translation:     #4338ca;
          --dot-active:      #4f46e5;
          --dot-inactive:    #d4d4d8;
          --glow-a:          rgba(79,70,229,0.07);
          --glow-b:          rgba(219,39,119,0.05);
          --glow-c:          rgba(5,150,105,0.04);
          --spinner-track:   #e4e4e7;
        }

        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
          font-family: 'DM Sans', -apple-system, sans-serif;
          -webkit-font-smoothing: antialiased;
          background: var(--bg);
          color: var(--text-primary);
          transition: background 0.3s, color 0.3s;
        }

        .page {
          min-height: 100vh;
          background: var(--bg);
          position: relative; overflow-x: hidden;
        }
        .page::before {
          content: ''; position: fixed; inset: 0;
          background:
            radial-gradient(ellipse 60% 40% at 20% 10%, var(--glow-a) 0%, transparent 60%),
            radial-gradient(ellipse 50% 40% at 80% 80%, var(--glow-b) 0%, transparent 60%),
            radial-gradient(ellipse 40% 30% at 60% 30%, var(--glow-c) 0%, transparent 50%);
          pointer-events: none; z-index: 0;
        }

        .layout {
          display: flex; min-height: 100vh;
          max-width: 1280px; margin: 0 auto;
          padding: 0 24px; position: relative; z-index: 1;
        }

        /* ── Sidebar ── */
        .sidebar {
          width: 220px; flex-shrink: 0; position: sticky; top: 0;
          height: 100vh; padding: 80px 0 40px;
          display: flex; flex-direction: column; gap: 2px;
        }
        .sidebar-label {
          font-size: 10px; font-weight: 600;
          letter-spacing: 0.12em; text-transform: uppercase;
          color: var(--text-muted); padding: 0 12px 12px;
        }
        .timeline-item {
          display: flex; align-items: center; gap: 10px;
          padding: 7px 12px; border-radius: 10px;
          cursor: pointer; border: none;
          background: transparent; font-family: 'DM Sans', sans-serif;
          text-align: left; width: 100%;
          transition: background 0.15s;
          position: relative;
        }
        .timeline-item:hover  { background: var(--bg-sidebar-hover); }
        .timeline-item.active { background: var(--bg-sidebar-active); }
        .timeline-dot {
          width: 7px; height: 7px; border-radius: 50%;
          background: var(--dot-inactive); flex-shrink: 0; transition: background 0.2s;
        }
        .timeline-item.active .timeline-dot {
          background: var(--dot-active);
          box-shadow: 0 0 0 3px color-mix(in srgb, var(--dot-active) 25%, transparent);
        }
        .timeline-text {
          font-size: 13px; font-weight: 500;
          color: var(--text-dim);
          white-space: nowrap; overflow: hidden; text-overflow: ellipsis; transition: color 0.2s;
        }
        .timeline-item.active .timeline-text { color: var(--accent-light); }
        .timeline-count {
          margin-left: auto; font-size: 11px; font-weight: 600;
          font-family: 'DM Mono', monospace; color: var(--text-faint); flex-shrink: 0;
        }
        .timeline-item.active .timeline-count { color: var(--accent); }
        .timeline-line {
          position: absolute; left: 18px; top: 22px;
          width: 1px; height: calc(100% + 2px);
          background: var(--border);
        }
        .sidebar-bottom {
          margin-top: auto; padding: 16px 12px;
          border-top: 1px solid var(--border);
        }
        .total-badge { font-size: 12px; color: var(--text-muted); font-family: 'DM Mono', monospace; }
        .total-badge span { color: var(--text-dim); }

        /* ── Main ── */
        .main { flex: 1; padding: 40px 0 80px 48px; min-width: 0; }

        /* ── Top bar ── */
        .top-bar {
          display: flex; align-items: flex-start; justify-content: space-between;
          margin-bottom: 40px; gap: 20px; flex-wrap: wrap;
        }
        .back-link {
          display: inline-flex; align-items: center; gap: 6px;
          font-size: 13px; font-weight: 500; color: var(--text-muted);
          text-decoration: none; transition: color 0.2s; margin-bottom: 10px;
        }
        .back-link:hover { color: var(--text-secondary); }
        .page-title { font-size: 36px; font-weight: 700; letter-spacing: -1px; color: var(--text-primary); line-height: 1.1; }
        .page-subtitle { font-size: 14px; color: var(--text-muted); margin-top: 4px; }
        .top-actions { display: flex; align-items: center; gap: 10px; flex-shrink: 0; margin-top: 4px; }

        /* ── Theme toggle ── */
        .btn-theme {
          width: 36px; height: 36px; border-radius: 10px;
          border: 1px solid var(--border-mid);
          background: var(--bg-btn);
          display: flex; align-items: center; justify-content: center;
          cursor: pointer; color: var(--text-dim);
          transition: all 0.2s; flex-shrink: 0;
          font-size: 16px;
        }
        .btn-theme:hover { background: var(--bg-btn-hover); color: var(--text-secondary); border-color: var(--border-high); }

        /* ── Search ── */
        .search-wrap { position: relative; }
        .search-input {
          background: var(--bg-input); border: 1px solid var(--border-mid);
          border-radius: 12px; padding: 9px 14px 9px 36px;
          font-size: 13px; font-family: 'DM Sans', sans-serif;
          color: var(--text-primary); width: 220px; outline: none; transition: all 0.2s;
        }
        .search-input::placeholder { color: var(--text-muted); }
        .search-input:focus { border-color: var(--accent); background: var(--bg-card); }
        .search-icon { position: absolute; left: 11px; top: 50%; transform: translateY(-50%); color: var(--text-muted); pointer-events: none; }

        /* ── Date range filter ── */
        .date-range-wrap {
          display: flex; align-items: center; gap: 6px;
          background: var(--bg-input); border: 1px solid var(--border-mid);
          border-radius: 12px; padding: 7px 12px;
          transition: border-color 0.2s;
        }
        .date-range-wrap:focus-within { border-color: var(--accent); }
        .date-icon { color: var(--text-muted); flex-shrink: 0; }
        .date-input {
          background: transparent; border: none; outline: none;
          font-size: 12px; font-family: 'DM Mono', monospace;
          color: var(--text-primary); width: 112px;
          cursor: pointer;
        }
        .date-input::-webkit-calendar-picker-indicator {
          opacity: 0.4; cursor: pointer; filter: var(--calendar-filter, none);
        }
        html[data-theme="dark"] { --calendar-filter: invert(1); }
        .date-sep { font-size: 12px; color: var(--text-faint); user-select: none; }
        .date-clear {
          display: flex; align-items: center; justify-content: center;
          width: 18px; height: 18px; border-radius: 50%;
          border: none; background: var(--border-high);
          color: var(--text-secondary); cursor: pointer;
          padding: 0; transition: all 0.15s; flex-shrink: 0;
        }
        .date-clear:hover { background: var(--accent-danger-bg); color: var(--accent-danger); }

        /* ── Clear filters button ── */
        .btn-clear-filters {
          background: none; border: none; cursor: pointer;
          font-size: 13px; color: var(--accent); font-family: 'DM Sans', sans-serif;
          text-decoration: underline; padding: 0;
        }
        .btn-clear-filters:hover { opacity: 0.75; }

        /* ── Export ── */
        .export-wrap { position: relative; }
        .btn-export {
          display: flex; align-items: center; gap: 7px; padding: 9px 16px;
          border-radius: 12px; border: 1px solid var(--border-mid);
          background: var(--bg-btn); font-size: 13px; font-weight: 600;
          color: var(--text-secondary); cursor: pointer; font-family: 'DM Sans', sans-serif;
          transition: all 0.2s;
        }
        .btn-export:hover { background: var(--bg-btn-hover); border-color: var(--border-high); color: var(--text-primary); }
        .export-menu {
          position: absolute; top: calc(100% + 8px); right: 0; z-index: 100;
          background: var(--bg-menu); border: 1px solid var(--border-mid);
          border-radius: 14px; padding: 6px; min-width: 160px;
          box-shadow: 0 16px 48px rgba(0,0,0,0.2);
          animation: fadeUp 0.15s ease;
        }
        @keyframes fadeUp { from{opacity:0;transform:translateY(4px)} to{opacity:1;transform:translateY(0)} }
        .export-option {
          display: flex; align-items: center; gap: 10px; width: 100%;
          padding: 10px 12px; border: none; border-radius: 9px;
          background: transparent; cursor: pointer; font-family: 'DM Sans', sans-serif;
          font-size: 13px; font-weight: 500; color: var(--text-secondary);
          transition: all 0.15s; text-align: left;
        }
        .export-option:hover { background: var(--bg-sidebar-hover); color: var(--text-primary); }
        .export-option-icon { width: 28px; height: 28px; border-radius: 7px; display: flex; align-items: center; justify-content: center; font-size: 14px; flex-shrink: 0; }
        .export-option-icon.json { background: rgba(251,191,36,0.15); }
        .export-option-icon.csv  { background: rgba(52,211,153,0.15); }
        .export-option-icon.md   { background: rgba(167,139,250,0.15); }
        .export-option-icon.pdf  { background: rgba(248,113,113,0.15); }
        .export-section-label { font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: var(--text-faint); padding: 4px 12px 2px; }
        .export-divider { height: 1px; background: var(--border); margin: 6px 0; }

        /* ── Groups ── */
        .group-section { margin-bottom: 48px; scroll-margin-top: 32px; }
        .group-header { display: flex; align-items: center; gap: 12px; margin-bottom: 16px; }
        .group-label { font-size: 11px; font-weight: 700; letter-spacing: 0.1em; text-transform: uppercase; color: var(--text-muted); }
        .group-divider { flex: 1; height: 1px; background: var(--border); }
        .group-count { font-size: 11px; font-family: 'DM Mono', monospace; color: var(--text-faint); }

        /* ── Record card ── */
        .record-card {
          background: var(--bg-card); border: 1px solid var(--border);
          border-radius: 16px; margin-bottom: 10px; overflow: hidden;
          transition: border-color 0.2s, background 0.2s;
        }
        .record-card:hover { background: var(--bg-card-hover); border-color: var(--border-mid); }
        .record-card.open  { border-color: var(--border-high); }

        .card-header { display: flex; align-items: center; gap: 14px; padding: 16px 20px; cursor: pointer; user-select: none; }
        .scenario-badge {
          width: 40px; height: 40px; border-radius: 11px;
          background: var(--bg-subtle); border: 1px solid var(--border-mid);
          display: flex; align-items: center; justify-content: center;
          font-size: 18px; flex-shrink: 0;
        }
        .card-meta { flex: 1; min-width: 0; }
        .card-scenario { font-size: 14px; font-weight: 600; color: var(--text-secondary); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
        .card-sub { display: flex; align-items: center; gap: 8px; margin-top: 3px; }
        .card-date { font-size: 12px; font-family: 'DM Mono', monospace; color: var(--text-muted); }
        .card-lang-pair { display: flex; align-items: center; gap: 4px; font-size: 12px; color: var(--text-muted); }
        .lang-arrow { color: var(--text-faint); font-size: 10px; }
        .lang-name { font-size: 11px; margin-left: 2px; color: var(--text-faint); }
        .dot-sep { width: 3px; height: 3px; border-radius: 50%; background: var(--border-high); }

        .card-summary-preview {
          flex: 1; min-width: 0; font-size: 13px; color: var(--text-muted);
          white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
          padding: 0 20px; display: none;
        }
        @media (min-width: 900px) { .card-summary-preview { display: block; } }

        .card-actions { display: flex; align-items: center; gap: 8px; flex-shrink: 0; }
        .btn-delete {
          width: 30px; height: 30px; border-radius: 8px; border: none;
          background: transparent; display: flex; align-items: center; justify-content: center;
          cursor: pointer; color: var(--text-faint); transition: all 0.2s;
        }
        .btn-delete:hover { background: var(--accent-danger-bg); color: var(--accent-danger); }
        .btn-delete.deleting { opacity: 0.5; cursor: not-allowed; }
        .expand-icon { color: var(--text-faint); transition: transform 0.25s; flex-shrink: 0; }
        .expand-icon.open { transform: rotate(180deg); }

        .card-body {
          border-top: 1px solid var(--border); padding: 20px;
          display: grid; grid-template-columns: 1fr 1fr; gap: 20px;
          animation: expandIn 0.22s ease;
        }
        @keyframes expandIn { from{opacity:0;transform:translateY(-4px)} to{opacity:1;transform:translateY(0)} }
        @media (max-width: 800px) { .card-body { grid-template-columns: 1fr; } }

        .body-section { display: flex; flex-direction: column; gap: 6px; }
        .body-section.full { grid-column: 1 / -1; }
        .body-label {
          font-size: 10px; font-weight: 700; text-transform: uppercase;
          letter-spacing: 0.1em; color: var(--text-faint);
          display: flex; align-items: center; gap: 5px;
        }
        .body-text { font-size: 14px; line-height: 1.65; color: var(--text-secondary); }
        .translation-text { color: var(--translation) !important; }
        .transcript-block {
          background: var(--bg-subtle); border: 1px solid var(--border);
          border-radius: 10px; padding: 12px 14px;
          font-size: 13px; font-family: 'DM Mono', monospace;
          color: var(--text-dim); line-height: 1.6;
        }
        .replies-grid { display: flex; flex-direction: column; gap: 6px; }
        .reply-chip { background: var(--bg-subtle); border: 1px solid var(--border-mid); border-radius: 10px; padding: 10px 12px; }
        .reply-native  { font-size: 13px; font-weight: 500; color: var(--text-secondary); }
        .reply-english { font-size: 12px; color: var(--text-muted); margin-top: 2px; font-family: 'DM Mono', monospace; }

        /* ── Per-card action buttons ── */
        .btn-action {
          display: flex; align-items: center; gap: 4px;
          height: 28px; padding: 0 9px;
          border-radius: 7px; border: 1px solid var(--border-mid);
          background: var(--bg-btn); cursor: pointer;
          color: var(--text-dim); font-family: 'DM Sans', sans-serif;
          transition: all 0.18s;
        }
        .btn-action:hover { background: var(--bg-btn-hover); color: var(--text-primary); border-color: var(--border-high); }
        .btn-action-label { font-size: 11px; font-weight: 700; letter-spacing: 0.02em; }

        /* ── States ── */
        .center-state { display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 60vh; gap: 12px; color: var(--text-faint); }
        .center-state-icon { font-size: 48px; opacity: 0.3; }
        .center-state-text { font-size: 15px; color: var(--text-dim); }
        .center-state-sub  { font-size: 13px; color: var(--text-muted); }
        .spinner {
          width: 28px; height: 28px; border-radius: 50%;
          border: 2px solid var(--spinner-track); border-top-color: var(--accent);
          animation: spin 0.8s linear infinite;
        }
        @keyframes spin { to { transform: rotate(360deg); } }
      `}</style>

      <div className="page">
        <div className="layout">

          {/* ── Timeline Sidebar ── */}
          <aside className="sidebar">
            <div className="sidebar-label">Timeline</div>
            {groups.map((g, i) => (
              <div key={g.key} style={{ position: "relative" }}>
                {i < groups.length - 1 && <div className="timeline-line" />}
                <button
                  className={`timeline-item ${activeGroup === g.key ? "active" : ""}`}
                  onClick={() => scrollToGroup(g.key)}
                >
                  <span className="timeline-dot" />
                  <span className="timeline-text">{g.label}</span>
                  <span className="timeline-count">{g.records.length}</span>
                </button>
              </div>
            ))}
            <div className="sidebar-bottom">
              <div className="total-badge"><span>{filtered.length}</span> sessions total</div>
            </div>
          </aside>

          {/* ── Main ── */}
          <main className="main">
            <div className="top-bar">
              <div>
                <a href="/" className="back-link">
                  <svg width="14" height="14" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                  </svg>
                  Back to Assistant
                </a>
                <div className="page-title">Call History</div>
                <div className="page-subtitle">Your past sessions, organized by time</div>
              </div>

              <div className="top-actions">
                {/* Search */}
                <div className="search-wrap">
                  <svg className="search-icon" width="14" height="14" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                  </svg>
                  <input className="search-input" placeholder="Search sessions..." value={search} onChange={e => setSearch(e.target.value)} />
                </div>

                {/* Date range filter */}
                <div className="date-range-wrap">
                  <svg className="date-icon" width="13" height="13" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                  </svg>
                  <input
                    type="date"
                    className="date-input"
                    value={dateFrom}
                    onChange={e => setDateFrom(e.target.value)}
                    title="From date"
                  />
                  <span className="date-sep">–</span>
                  <input
                    type="date"
                    className="date-input"
                    value={dateTo}
                    onChange={e => setDateTo(e.target.value)}
                    title="To date"
                  />
                  {(dateFrom || dateTo) && (
                    <button className="date-clear" onClick={() => { setDateFrom(""); setDateTo(""); }} title="Clear dates">
                      <svg width="12" height="12" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M6 18L18 6M6 6l12 12" />
                      </svg>
                    </button>
                  )}
                </div>

                {/* Export */}
                <div className="export-wrap" ref={exportRef}>
                  <button className="btn-export" onClick={() => setShowExport(v => !v)}>
                    <svg width="14" height="14" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                    </svg>
                    Export
                  </button>
                  {showExport && (
                    <div className="export-menu">
                      <div className="export-section-label">Data</div>
                      <button className="export-option" onClick={() => { exportJSON(filtered); setShowExport(false); }}>
                        <span className="export-option-icon json">{ }</span>
                        <div>
                          <div style={{ color: "#fbbf24", fontWeight: 600 }}>JSON</div>
                          <div style={{ fontSize: 11, color: "var(--text-muted)" }}>Full data</div>
                        </div>
                      </button>
                      <button className="export-option" onClick={() => { exportCSV(filtered); setShowExport(false); }}>
                        <span className="export-option-icon csv">📊</span>
                        <div>
                          <div style={{ color: "#34d399", fontWeight: 600 }}>CSV</div>
                          <div style={{ fontSize: 11, color: "var(--text-muted)" }}>Spreadsheet</div>
                        </div>
                      </button>
                      <div className="export-divider" />
                      <div className="export-section-label">Report</div>
                      <button className="export-option" onClick={() => { exportAllMarkdown(filtered); setShowExport(false); }}>
                        <span className="export-option-icon md">📄</span>
                        <div>
                          <div style={{ color: "#a78bfa", fontWeight: 600 }}>Markdown</div>
                          <div style={{ fontSize: 11, color: "var(--text-muted)" }}>All sessions</div>
                        </div>
                      </button>
                      <button className="export-option" onClick={() => { exportAllPDF(filtered); setShowExport(false); }}>
                        <span className="export-option-icon pdf">🖨️</span>
                        <div>
                          <div style={{ color: "#f87171", fontWeight: 600 }}>PDF</div>
                          <div style={{ fontSize: 11, color: "var(--text-muted)" }}>Print / save</div>
                        </div>
                      </button>
                    </div>
                  )}
                </div>

                {/* Theme toggle */}
                <button suppressHydrationWarning className="btn-theme" onClick={toggleTheme} title={`Switch to ${theme === "dark" ? "light" : "dark"} mode`}>
                  {theme === "dark" ? "☀️" : "🌙"}
                </button>
              </div>
            </div>

            {/* States */}
            {loading && (
              <div className="center-state">
                <div className="spinner" />
                <div className="center-state-text">Loading sessions...</div>
              </div>
            )}
            {!loading && filtered.length === 0 && (
              <div className="center-state">
                <div className="center-state-icon">📭</div>
                <div className="center-state-text">{hasActiveFilters ? "No sessions match your filters" : "No sessions yet"}</div>
                <div className="center-state-sub">{hasActiveFilters ? <button className="btn-clear-filters" onClick={clearFilters}>Clear all filters</button> : "Start a call to see history here"}</div>
              </div>
            )}

            {/* Groups */}
            {!loading && groups.map(group => (
              <section
                key={group.key}
                className="group-section"
                data-group={group.key}
                ref={el => { sectionRefs.current[group.key] = el; }}
              >
                <div className="group-header">
                  <span className="group-label">{group.label}</span>
                  <div className="group-divider" />
                  <span className="group-count">{group.records.length}</span>
                </div>

                {group.records.map(record => {
                  const isOpen   = expanded === record.id;
                  const icon     = SCENARIO_ICONS[record.scenario] ?? "📞";
                  const srcFlag  = getFlag(record.source_language ?? "English");
                  const tgtFlag  = getFlag(record.target_language ?? "Chinese (中文)");
                  const srcShort = (record.source_language ?? "").split(" ")[0];
                  const tgtShort = (record.target_language ?? "").split(" ")[0];

                  return (
                    <div key={record.id} className={`record-card ${isOpen ? "open" : ""}`}>
                      <div className="card-header" onClick={() => setExpanded(isOpen ? null : record.id)}>
                        <div className="scenario-badge">{icon}</div>
                        <div className="card-meta">
                          <div className="card-scenario">{record.scenario}</div>
                          <div className="card-sub">
                            <span className="card-date">{record.date}</span>
                            <span className="dot-sep" />
                            <span className="card-lang-pair">
                              {srcFlag} <span className="lang-arrow">→</span> {tgtFlag}
                              <span className="lang-name">{srcShort} → {tgtShort}</span>
                            </span>
                          </div>
                        </div>
                        <div className="card-summary-preview">{record.summary}</div>
                        <div className="card-actions">
                          {/* Export MD */}
                          <button
                            className="btn-action"
                            onClick={e => { e.stopPropagation(); exportSessionMarkdown(record); }}
                            title="Export as Markdown"
                          >
                            <svg width="13" height="13" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
                            </svg>
                            <span className="btn-action-label">.md</span>
                          </button>
                          {/* Export PDF */}
                          <button
                            className="btn-action"
                            onClick={e => { e.stopPropagation(); exportSessionPDF(record); }}
                            title="Export as PDF"
                          >
                            <svg width="13" height="13" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                            </svg>
                            <span className="btn-action-label">PDF</span>
                          </button>
                          {/* Delete */}
                          <button
                            className={`btn-delete ${deletingId === record.id ? "deleting" : ""}`}
                            onClick={e => { e.stopPropagation(); handleDelete(record.id); }}
                            disabled={deletingId === record.id}
                            title="Delete"
                          >
                            <svg width="14" height="14" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                            </svg>
                          </button>
                          <svg className={`expand-icon ${isOpen ? "open" : ""}`} width="16" height="16" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                          </svg>
                        </div>
                      </div>

                      {isOpen && (
                        <div className="card-body">
                          <div className="body-section">
                            <div className="body-label">
                              <svg width="11" height="11" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
                              Summary
                            </div>
                            <p className="body-text">{record.summary}</p>
                          </div>
                          <div className="body-section">
                            <div className="body-label">{srcFlag} → {tgtFlag} Translation</div>
                            <p className="body-text translation-text">{record.translation}</p>
                          </div>
                          <div className="body-section full">
                            <div className="body-label">
                              <svg width="11" height="11" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" /></svg>
                              Transcript
                            </div>
                            <div className="transcript-block">{record.transcript}</div>
                          </div>
                          {record.replies?.length > 0 && (
                            <div className="body-section full">
                              <div className="body-label">
                                <svg width="11" height="11" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" /></svg>
                                Suggested Replies
                              </div>
                              <div className="replies-grid">
                                {record.replies.map((reply, i) => {
                                  const parts = reply.split("\n").map(p => p.trim()).filter(Boolean);
                                  return (
                                    <div key={i} className="reply-chip">
                                      <div className="reply-native">{parts[0]}</div>
                                      {parts[1] && <div className="reply-english">{parts[1]}</div>}
                                    </div>
                                  );
                                })}
                              </div>
                            </div>
                          )}
                        </div>
                      )}
                    </div>
                  );
                })}
              </section>
            ))}
          </main>
        </div>
      </div>
    </>
  );
}